#############################################################################
# Makefile for building: MoniApp.app/Contents/MacOS/MoniApp
# Generated by qmake (2.01a) (Qt 4.7.3) on: Sat May 21 04:28:32 2011
# Project:  MoniApp.pro
# Template: app
# Command: /Developer/Qt/Desktop/Qt/473/gcc/bin/qmake -spec /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++ CONFIG+=release QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile MoniApp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++ -I. -I/Developer/Qt/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I/Developer/Qt/Desktop/Qt/473/gcc/include/QtCore -I/Developer/Qt/Desktop/Qt/473/gcc/lib/QtGui.framework/Versions/4/Headers -I/Developer/Qt/Desktop/Qt/473/gcc/include/QtGui -I/Developer/Qt/Desktop/Qt/473/gcc/include -I. -I. -F/Developer/Qt/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Developer/Qt/Desktop/Qt/473/gcc/lib -L/Developer/Qt/Desktop/Qt/473/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/Qt/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		SideBar.cpp moc_MainWindow.cpp \
		moc_SideBar.cpp \
		qrc_MoniAppIcons.cpp
OBJECTS       = main.o \
		MainWindow.o \
		SideBar.o \
		moc_MainWindow.o \
		moc_SideBar.o \
		qrc_MoniAppIcons.o
DIST          = /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		MoniApp.pro
QMAKE_TARGET  = MoniApp
DESTDIR       = 
TARGET        = MoniApp.app/Contents/MacOS/MoniApp

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile MoniApp.app/Contents/PkgInfo MoniApp.app/Contents/Resources/empty.lproj MoniApp.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_MainWindow.h ui_SideBar.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) MoniApp.app/Contents/MacOS/ || $(MKDIR) MoniApp.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MoniApp.pro  /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++/qmake.conf /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++ CONFIG+=release QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile MoniApp.pro
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/release.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
/Developer/Qt/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++ CONFIG+=release QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/Developer/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile MoniApp.pro

MoniApp.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) MoniApp.app/Contents || $(MKDIR) MoniApp.app/Contents 
	@$(DEL_FILE) MoniApp.app/Contents/PkgInfo
	@echo "APPL????" >MoniApp.app/Contents/PkgInfo
MoniApp.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) MoniApp.app/Contents/Resources || $(MKDIR) MoniApp.app/Contents/Resources 
	@touch MoniApp.app/Contents/Resources/empty.lproj
	
MoniApp.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) MoniApp.app/Contents || $(MKDIR) MoniApp.app/Contents 
	@$(DEL_FILE) MoniApp.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,MoniApp,g" -e "s,@TYPEINFO@,????,g" /Developer/Qt/Desktop/Qt/473/gcc/mkspecs/macx-g++/Info.plist.app >MoniApp.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/MoniApp1.0.0 || $(MKDIR) .tmp/MoniApp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MoniApp1.0.0/ && $(COPY_FILE) --parents MainWindow.h SideBar.h .tmp/MoniApp1.0.0/ && $(COPY_FILE) --parents MoniAppIcons.qrc .tmp/MoniApp1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp SideBar.cpp .tmp/MoniApp1.0.0/ && $(COPY_FILE) --parents MainWindow.ui SideBar.ui .tmp/MoniApp1.0.0/ && (cd `dirname .tmp/MoniApp1.0.0` && $(TAR) MoniApp1.0.0.tar MoniApp1.0.0 && $(COMPRESS) MoniApp1.0.0.tar) && $(MOVE) `dirname .tmp/MoniApp1.0.0`/MoniApp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MoniApp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r MoniApp.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_MainWindow.cpp moc_SideBar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_SideBar.cpp
moc_MainWindow.cpp: MainWindow.h
	/Developer/Qt/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MainWindow.h -o moc_MainWindow.cpp

moc_SideBar.cpp: SideBar.h
	/Developer/Qt/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ SideBar.h -o moc_SideBar.cpp

compiler_rcc_make_all: qrc_MoniAppIcons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_MoniAppIcons.cpp
qrc_MoniAppIcons.cpp: MoniAppIcons.qrc \
		icons/add.png \
		icons/config.png
	/Developer/Qt/Desktop/Qt/473/gcc/bin/rcc -name MoniAppIcons MoniAppIcons.qrc -o qrc_MoniAppIcons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_SideBar.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_SideBar.h
ui_MainWindow.h: MainWindow.ui \
		SideBar.h
	/Developer/Qt/Desktop/Qt/473/gcc/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_SideBar.h: SideBar.ui
	/Developer/Qt/Desktop/Qt/473/gcc/bin/uic SideBar.ui -o ui_SideBar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainWindow.h \
		SideBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

SideBar.o: SideBar.cpp SideBar.h \
		ui_SideBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SideBar.o SideBar.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_SideBar.o: moc_SideBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SideBar.o moc_SideBar.cpp

qrc_MoniAppIcons.o: qrc_MoniAppIcons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_MoniAppIcons.o qrc_MoniAppIcons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

